# rubocop --auto-gen-config
require:
  - rubocop-performance
  - rubocop-rails

AllCops:
  TargetRubyVersion: 2.6.2
  Exclude:
    - bin/**/*
    - db/schema.rb
    - docs/**/*
    - node_modules/**/*

Style/Documentation:
  Enabled: false

Rails:
  Enabled: true

Rails/ApplicationRecord:
  Enabled: false

Rails/RequestReferer:
  EnforcedStyle: referrer

Rails/HttpPositionalArguments:
  Exclude:

Metrics/BlockLength:
  Exclude:
    - Rakefile
    - '**/*.rake'
    - db/migrate/*.rb
  IgnoredMethods: [class_methods]

Metrics/LineLength:
  Enabled: true
  Max: 120

Style/ClassAndModuleChildren:
  Enabled: false

Style/RegexpLiteral:
  Enabled: false

Layout/EmptyLineAfterMagicComment:
  Enabled: false

Naming/RescuedExceptionsVariableName:
  PreferredName: error